FROM openjdk:8-jdk


RUN apt-get update && apt-get install -y apache2

EXPOSE 80

# Copy your web application to the Apache document root
COPY /path/to/your/webapp /var/www/html/


# Start Apache server
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]


docker build -t Oxygene_Fitness .

docker run -d -p 80:80 Oxygene_Fitness
